const arr = ["aviators",
"milb_fishercats",
"milb_fireflies",
"milb_quakes",
"milb_rivercats",
"milb_chihuahuas",
"milb_drive",
"milb_sounds",
"milb_hops",
"milb_bulls",
"nba_spurs",
"nba_timberwolves",
"ahl_admirals",
"milb_seadogs",
"milb_stormchasers",
"milb_windsurge",
"nba_hawks",
"nba_raptors",
"nhl_leafs",
"mlse",
"nhl_panthers",
"nba_76ers",
"nba_thunder",
"nba_bucks",
"tennis_bnp",
"mp_bse",
"nba_nets",
"wnba_liberty",
"barclays_center",
"mp_cebl",
"cebl_surge",
"cebl_stingers",
"cebl_rattlers",
"cebl_honeybadgers",
"cebl_riverlions",
"cebl_shootingstars",
"cebl_alliance",
"cebl_seabears",
"cfl_redblacks",
"ohl_67s",
"nhl_redwings",
"mlb_tigers",
"mls_tfc",
"nhl_kings",
"tennis_wso",
"cfl_argos",
"nba_mavericks",
"nba_rockets"]

const sorted = arr.sort()

console.log(sorted)


[
    "ahl_admirals",
    "aviators",
    "barclays_center",
    "cebl_alliance",
    "cebl_honeybadgers",
    "cebl_rattlers",
    "cebl_riverlions",
    "cebl_seabears",
    "cebl_shootingstars",
    "cebl_stingers",
    "cebl_surge",
    "cfl_argos",
    "cfl_redblacks",
    "milb_bulls",
    "milb_chihuahuas",
    "milb_drive",
    "milb_fireflies",
    "milb_fishercats",
    "milb_hops",
    "milb_quakes",
    "milb_rivercats",
    "milb_seadogs",
    "milb_sounds",
    "milb_stormchasers",
    "milb_windsurge",
    "mlb_tigers",
    "mls_tfc",
    "mlse",
    "mp_bse",
    "mp_cebl",
    "nba_76ers",
    "nba_bucks",
    "nba_hawks",
    "nba_mavericks",
    "nba_nets",
    "nba_raptors",
    "nba_rockets",
    "nba_spurs",
    "nba_thunder",
    "nba_timberwolves",
    "nhl_kings",
    "nhl_leafs",
    "nhl_panthers",
    "nhl_redwings",
    "ohl_67s",
    "tennis_bnp",
    "tennis_wso",
    "wnba_liberty"
  ]

//   "ahl_admirals",
//   "aviators",
//   "barclays_center",
//   "cebl_alliance",
//   "cebl_honeybadgers",
//   "cebl_rattlers",
//   "cebl_riverlions",
//   "cebl_seabears",
//   "cebl_shootingstars",
//   "cebl_stingers",
//   "cebl_surge",
//   "cfl_argos",
//   "milb_bulls",
//   "milb_chihuahuas",
//   "milb_fireflies",
//   "milb_fishercats",
//   "milb_hops",
//   "milb_quakes",
//   "milb_rivercats",
//   "milb_seadogs",
//   "milb_sounds",
//   "milb_windsurge",
//   "mlb_tigers",
//   "mls_tfc",
//   "mlse",
//   "mp_bse",
//   "mp_cebl",
//   "nba_76ers",
//   "nba_bucks",
//   "nba_hawks",
//   "nba_mavericks",
//   "nba_nets",
//   "nba_raptors",
//   "nba_rockets",
//   "nba_spurs",
//   "nba_thunder",
//   "nba_timberwolves",
//   "nhl_kings",
//   "nhl_leafs",
//   "nhl_panthers",
//   "nhl_redwings",
//   "tennis_bnp",
//   "tennis_wso",
//   "wnba_liberty"